Allowed additional music.stanford.edu .html redirect path in .htaccess.
SU-HSDO/suhumsci pull request #1182
Opened 2022-09-20 19:18 UTC by joegl

# READY FOR REVIEW

## Summary
- Allowed additional music.stanford.edu .html redirect path in .htaccess.

Original request:
```
Afternoon, we you put in an exception to allow for an HTML link on the Music site. Could we please put in a second one?  I thought we had resolved it by changing the domain redirect, but this URL got printed on paper and delivered in people's mailboxes.
https://music.stanford.edu/FOM/fom.html
```

## Need Review By (Date)
_['10/30', 'asap', etc.]_

## Urgency
_['low', 'medium', 'high', etc.]_

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2022-09-20 19:20 UTC, su-sws-jira commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1182-nitual6qyz4jmt723v0cts6ly0pvvinl.tugboatqa.com
- https://hs-colorful-nitual6qyz4jmt723v0cts6ly0pvvinl.tugboatqa.com
- https://hs-traditional-nitual6qyz4jmt723v0cts6ly0pvvinl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/632a11ffd65209e3aac88836

2022-09-20 19:57 UTC, pookmish requested changes
Be sure to update the htaccess patch file

2022-09-20 20:53 UTC, su-sws-jira commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1182-nitual6qyz4jmt723v0cts6ly0pvvinl.tugboatqa.com
- https://hs-colorful-nitual6qyz4jmt723v0cts6ly0pvvinl.tugboatqa.com
- https://hs-traditional-nitual6qyz4jmt723v0cts6ly0pvvinl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/632a11ffd65209e3aac88836

2022-09-20 20:58 UTC, joegl commented
> Be sure to update the htaccess patch file

Should be in now.

2022-09-20 21:01 UTC, su-sws-jira commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1182-nitual6qyz4jmt723v0cts6ly0pvvinl.tugboatqa.com
- https://hs-colorful-nitual6qyz4jmt723v0cts6ly0pvvinl.tugboatqa.com
- https://hs-traditional-nitual6qyz4jmt723v0cts6ly0pvvinl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/632a11ffd65209e3aac88836

2022-09-22 20:41 UTC, pookmish approved these changes

2022-09-22 20:41 UTC, merged