FourKitchens Release: Sprint 21
SU-HSDO/suhumsci pull request #1277
Opened 2023-03-16 22:46 UTC by callinmullaney

# READY FOR REVIEW

## Summary
- SHS-148: Implement image optimize module to improve image compression pipelines and decrease file sizes across all sites
- SHS-4648: Fix a z-index issue with image caption appear above event date badges

## Need Review By (Date)
3/20

## Urgency
low

## Steps to Test
1. Go to 

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2023-03-22 00:30 UTC, pookmish commented on composer.json
> +        "drupal/imageapi_optimize_resmushit": "^2.0@beta",
What do  these do that imagemagick doesn't? These seems like just additional bloat

2023-03-27 14:30 UTC, callinmullaney commented
@pookmish You're correct that the two additional modules were adding some overlapping functionality that already exists with imagemagik. I reworked this release to exclude those modules but kept the core `imageapi_optimize` present. The reason here is the existing WebP module only affects responsive images. However, there are many instances (mostly views) where a responsive image is not in use and an image style is used directly. With the `imageapi_optimize` I have a WebP pipeline available to assign to all image styles. With this default pipleline in place and the small changes to the image toolkit config we're still getting improved Google Page Speed scores with smaller image file sizes and images served in next-gen formats. 
Back to you!

2023-03-28 16:08 UTC, pookmish requested changes
This doesn't do anything to improve image performance other than decrease the derived quality by 10%. Sure you have a "pipeline" set up for a webp image, but the jpg/png is still loaded to the browser. 
Decreasing image quality is not a satisfactory solution to improve performance. Please revise.

2023-03-29 22:04 UTC, callinmullaney commented
@pookmish closing this PR. Given the image pipeline isn't producing the expected results here we'll take a new approach that adds a convert filter for image styles directly. This will result in more configuration changes but should produce the desired markup output. 
We have another PR open and internally testing that adds a lot more responsive image styles and new basic image styles that are more specific for individual components. This is helping performance in a manner where we are no longer serving images in larger resolutions and down-scaling them with CSS: https://github.com/SU-HSDO/suhumsci/pull/1256
That being said, the image compression changes here are having a measurable affect on page sizes which directly affect page performance. I'd like to push forward with those specific adjustment as they do not visually affect the image quality but result in smaller files.

2023-03-29 22:04 UTC, closed without merging