shs-4860: js to capture search terms and expand timeline/accord
SU-HSDO/suhumsci pull request #1292
Opened 2023-04-12 19:15 UTC by ryanhagerty

## Summary
This will append a user's search query to their search result links. When they click on a search result, if the page contains collapsed accordion or timeline components containing that search phrase, it will automatically expand them. 

## Steps to Test
1. Go to an accordion component page (`/components/accordions-secondary`) and a timeline component page (`/components/vertical-timeline-without-and-collection`).
2. Edit those pages and within a couple of the components, add a unique search term. I added 'Pepperoni pizza'. Make sure to include the term in a collection or well for testing.
3. Reindex your local search.
4. Use the search toolbar in the header to search for the term you just inserted.
5. Click on the search results. Notice how the accordion/timeline components that contain your search are automatically expanded. Click expand/collapse buttons to make sure original functionality is intact.
6. Visit a regular page and visit the accordion/timeline pages **without** the appended query params in the URL. Check the console to ensure their are no errors. 

## Screenshots
![Screenshot 2023-04-12 at 3 06 09 PM](https://user-images.githubusercontent.com/8405274/231561498-5b8df93e-7408-4f2a-a807-9bcaee785f06.png)

## Notes
* There is no new twig template. There's so hair preprocessing going on in the background again so the theme suggestion for creating a views search is not working. There exists a pre-existing twig template that's used for searches, so I included the JS there. I 'if'ed the function in case this template is mysteriously used elsewhere. I cannot tell.

2023-04-14 14:13 UTC, callinmullaney requested changes
@ryanhagerty This PR looks pretty good. Functionally it's working as expected and the JS you wrote isn't throwing errors when looking at non-search views. However, that `view-view-unformatted.html.twig` is used for pretty much every view on the platform. It's rendered one layer deeper than the standard `views-view.html.twig` template. Because of this reason I think we should try and only attach it to the search view specifically. You can do this via the following template suggestion: 
```
/**
 * Implements hook_theme_suggestions_alter().
 *
 * Add form login template suggestions.
 *
 * @inheritdoc
 */
function humsci_basic_suggestions_alter(&$suggestions, $variables, $hook) {
  if ($hook == 'views_view') {
    $suggestions[] = 'views_view__' . $variables['view']->id();
    $suggestions[] = 'views_view__' . $variables['view']->id() . $variables['view']->current_display;
  }
}
``` 
This should allow you to create a unique template along the lines of: `views-view--hs-default-search.html.twig`
OR
Use the following preprocessing function to attach it directly:
```
/**
 * Implements hook_preprocess_views_view().
 */
function humsci_basic_preprocess_views_view(&$variables) {
  $view = $variables['view'];

  switch ($view->id()) {
    case 'hs_default_search':
     $variables['#attached']['library'][] =  'humsci_basic/search';
      break;
  }
}
```

2023-04-18 19:53 UTC, callinmullaney approved these changes
@ryanhagerty Thanks for making that change. Preprocess function looks good and confirmed in devTools the JS file isn't loading for non-search views.

2023-04-18 19:54 UTC, callinmullaney commented
@pookmish This PR is ready for you. Functionality is meeting our acceptance criteria and the code Ryan authored looks good to me. Kicking this over to you for a once-over and merge into the next release.

2023-04-19 17:12 UTC, pookmish approved these changes

2023-04-19 17:12 UTC, merged