HSD8-513 added color background option to text area paragraph
SU-HSDO/suhumsci pull request #143
Opened 2018-11-30 22:55 UTC by pookmish

2018-12-06 17:25 UTC, pookmish commented
!(poke)[https://66.media.tumblr.com/a1f42c7b213265bde529ca41bd6c7e63/tumblr_npkg3ksc1a1un30xeo1_400.gif]

2018-12-07 20:50 UTC, sherakama commented on config/default/core.entity_view_display.paragraph.hs_text_area.default.yml
> +        class: 'color-[paragraph:field_hs_text_area_bg_color]'
These are not the most semantic names but I see why you did this. I think for H&S this is fine but overall, these should have human-readable labels.

2018-12-07 20:55 UTC, sherakama commented on docroot/modules/humsci/hs_paragraph_types/modules/hs_text_area/scss/hs_text_area.scss
> +@import 'colors', 'decanter-no-markup';
This should have charset declared at the top of the file.

2018-12-07 20:56 UTC, sherakama commented on docroot/modules/humsci/hs_paragraph_types/modules/hs_text_area/scss/_colors.scss
> +@mixin text-area-colors($color) {
Mixins should have docblock style comments.

2018-12-07 20:56 UTC, sherakama commented on docroot/modules/humsci/hs_paragraph_types/modules/hs_text_area/scss/_colors.scss
> +
Missing charset declaration.

2018-12-07 20:56 UTC, sherakama commented on docroot/modules/humsci/hs_paragraph_types/modules/hs_text_area/package.json
> +  "name": "su_humsci_theme",
Thi is not the theme. Please change package name.

2018-12-07 20:57 UTC, sherakama commented on docroot/modules/humsci/hs_paragraph_types/modules/hs_text_area/package.json
> +  "repository": "https://github.com/SU-HSDO/suhumsci",
This is not the repo

2018-12-07 20:57 UTC, sherakama commented on docroot/modules/humsci/hs_paragraph_types/modules/hs_text_area/package.json
> +    "grunt-autoprefixer": "^3.0.3",
We need to update our standard file, this is out of date. grunt-autoprefixer is out and autoprefixer is in.

2018-12-07 20:57 UTC, sherakama commented on docroot/modules/humsci/hs_paragraph_types/modules/hs_text_area/hs_text_area.module
> +    $build['#attached']['library'][] = 'hs_text_area/hs_text_area';
Yay, libraries.

2018-12-07 20:58 UTC, sherakama commented on docroot/modules/humsci/hs_paragraph_types/modules/hs_text_area/hs_text_area.libraries.yml
> +    base:
This seems like a 'theme' layer change.

2018-12-07 20:59 UTC, sherakama commented on docroot/modules/humsci/hs_paragraph_types/modules/hs_text_area/Gruntfile.js
> +  grunt.loadNpmTasks('grunt-drush');
This is not compatible with all local systems. Please remove drush.

2018-12-07 20:59 UTC, sherakama requested changes
Please see comments.

2018-12-08 00:28 UTC, pookmish commented on config/default/core.entity_view_display.paragraph.hs_text_area.default.yml
> +        class: 'color-[paragraph:field_hs_text_area_bg_color]'
So the field that the token is coming from is actually a color field. And the data is stored as the value. It's a great module but that was my only dislike. Could add some altering if necessary in the future

2018-12-08 00:29 UTC, pookmish commented on docroot/modules/humsci/hs_paragraph_types/modules/hs_text_area/scss/hs_text_area.scss
> +@import 'colors', 'decanter-no-markup';
This is what you get for having a back end developer do front end work 😁

2018-12-12 01:09 UTC, boznik commented
This is working as expected. GTG by me when shea's changes are addressed

2018-12-12 14:46 UTC, sherakama approved these changes
GTG

2018-12-12 14:46 UTC, merged