SHS-5515): Implementation: Adjustments to vertical cards
SU-HSDO/suhumsci pull request #1487
Opened 2024-03-21 20:53 UTC by mariannuar

# READY FOR REVIEW

## Summary
Adjustments to vertical cards

## Need Review By (Date)
03/22

## Urgency
medium

## Steps to Test
1. Go to this pages
  - https://hs-colorful.suhumsci.loc/collections-cards-continued
  - https://hs-colorful.suhumsci.loc/mixed-pages/mixed-page-raised-cards
  - https://hs-traditional.suhumsci.loc/collections-cards-continued
  - https://hs-traditional.suhumsci.loc/mixed-pages/mixed-page-raised-cards
 2. .....

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-03-25 00:19 UTC, cienvaras requested changes
@mariannuar I fixed some minor issues, but I'm still having some problems with the heading level in views. Let's regroup on Monday to check the best way to fix it.

2024-03-27 18:09 UTC, mariannuar commented
@cienvaras I think I got it working. Let me know what do you think. Thanks! :)

2024-04-01 16:24 UTC, cienvaras requested changes
@mariannuar Needs some work, please let me know if you have any questions

2024-04-01 16:24 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/humsci_basic.theme
> +    $variables['title']['#markup'] = $title_rendered;
It would be better to do this with DOMDocument instead of a regex.

2024-04-01 16:24 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/humsci_basic.theme
> +      $variables['href'] = $links->item(0)->nodeValue;
Did you updated the vertical linked card template to match the new variable name?

2024-04-04 16:25 UTC, cienvaras approved these changes
Looks great, thanks!

2024-04-04 16:25 UTC, merged