SHS-5582: Bug: Issue with Add/Select Media form field
SU-HSDO/suhumsci pull request #1511
Opened 2024-04-23 23:19 UTC by mariannuar

# READY FOR REVIEW

## Summary
Fix the "Sort by" label and form field that has incorrect styling when site editor uses the Media Library in CKEditor

## Need Review By (Date)
04/03

## Urgency
low

## Steps to Test
1. Create a Flexible Page on Colorfun and Traditional
2. Select the Media Library in CKEditor and confirm the "Sort by" label and form field looks like this
3. Confirm any select/combox still looks as expected in other forms (Views for example)

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-04-26 21:17 UTC, cienvaras requested changes
@mariannuar Thanks! Some fixes needed though, please check the inline comments.

2024-04-26 21:17 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/admin/_wysiwyg-editor.scss
> +body.gin--edit-form .views-exposed-form .select-preact {
Please move the code to `docroot/themes/humsci/su_humsci_gin_admin/dist/su_humsci_gin_admin.css`. That's the place to add admin theme styles.

2024-04-26 21:17 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/admin/_wysiwyg-editor.scss
> +  }
This is not what we need. We still want to use the preact plugin (it has extra features —like search— that can be useful), but it should look like the regular select.

2024-04-26 23:22 UTC, mariannuar commented
@cienvaras Thank you for your feedback! Now the preact plugin is looking similar to the regular select.

2024-04-29 20:31 UTC, cienvaras requested changes
@mariannuar We're almost there, but there are still some inconsistencies that can be easily fixed:

- Label's line height should be 18px
- Button's vertical padding should be 7px, instead of 8px
- Border radius is smaller than other elements

Please use Gin CSS variables when available.

2024-04-29 20:31 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/admin/_wysiwyg-editor.scss
> +}
Please remove this change.

2024-04-29 20:31 UTC, cienvaras commented on docroot/themes/humsci/su_humsci_gin_admin/dist/su_humsci_gin_admin.css
> +  color: #222330;
Gin has variables for most if its properties, please use them when available. In this case, `var(--gin-color-title)`.

2024-04-30 16:53 UTC, mariannuar commented
@cienvaras Thanks! Using gin variables now.

2024-05-02 13:09 UTC, cienvaras approved these changes
Looks great, thanks! 🚀

2024-05-02 13:10 UTC, merged