SHS-5623: Update styles for Date Stacked Vertical Card pattern
SU-HSDO/suhumsci pull request #1519
Opened 2024-05-07 01:23 UTC by mariannuar

# READY FOR REVIEW

## Summary
Updates for Date Stacked Vertical Card and reuse code

## Need Review By (Date)
05/17

## Urgency
medium

## Steps to Test
1. Visit the following pages on Colorful and Traditional

-  `/mixed-pages/mixed-page-raised-cards`
-  `/collections-cards-continued`

2. Confirm the Date Stacked Vertical Card works and looks as expected on [Figma Option C](https://fourkitchens.clickup.com/t/36718269/SHS-5623#:~:text=UX/Design%20Tickets%20Work)
3. Since we are reusing code for `Vertical Card`, `Vertical Linked Card` and `Date Stacked Vertical Card` please, confirm all of them still look and work as they were before

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-05-13 16:15 UTC, cienvaras requested changes
@mariannuar Looks good! There are a couple of small things to review though, please check the comments on the code.

2024-05-13 16:15 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/humsci_basic.theme
> +    _humsci_basic_make_title_the_link($variables);
Please check line 210 if this file. There's some logic there that's specific to the postcards. You may need to add an extra condition to ensure that there are no issues in other patterns.

2024-05-13 16:15 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/js/shared/linked-cards/linked-cards.js
> +    if (card.querySelector('.hb-card__title a')) {
I think you're missing the logic for the date stacked card here.

2024-05-13 16:15 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/js/shared/linked-cards/linked-cards.js
> +function linkedCards() {
No need to use a named function here. Please switch to using [a closure](https://www.drupal.org/docs/develop/standards/javascript-coding-standards/javascript-coding-standards#strict)

2024-05-13 21:41 UTC, mariannuar commented on docroot/themes/humsci/humsci_basic/humsci_basic.theme
> +    _humsci_basic_make_title_the_link($variables);
@cienvaras I checked and you were right, this piece of code is only happening for postcards. Didn't find issues in other patterns, the condition is working as expected.

2024-05-13 21:42 UTC, mariannuar commented
@cienvaras I fixed everything and this is ready for review again. Thanks!

2024-05-16 16:52 UTC, cienvaras approved these changes
Works great, thanks for the fixes! 🚀

2024-05-16 16:53 UTC, merged