SHS-5619: CSS Code Cleanup: Icon mixins cleanup and improvements
SU-HSDO/suhumsci pull request #1550
Opened 2024-06-10 15:10 UTC by mariannuar

# READY FOR REVIEW

## Summary
Icon mixins cleanup and improvements

## Need Review By (Date)
06/14

## Urgency
medium

## Steps to Test
1. On Colorful and Traditional, visit pages that have patterns carousels and cards with icons
2. Confirm the icons still look good

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-06-13 00:55 UTC, cienvaras requested changes
@mariannuar Looks great! I just left a couple of small change request, nothing big.

Please notice that I merged the "Theme assets compile" code in this branch. The main change is that you don't have to include the compiled css/js in git. Let me know if you have any question on the changes or how to make everything work.

2024-06-13 00:55 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.icons.scss
> +@mixin hb-icon-link-arrow($color: 'black', $drop-shadow: false) {
@mariannuar For consistency with the original mixin, let's change the variable name to `$box-shadow` please.

2024-06-13 00:55 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.icons.scss
> +@mixin hb-icon-type($icon, $color) {
Please change `$icon` to `$type`. I think it's more clear because its what's used in the mixin name.

2024-06-13 20:08 UTC, mariannuar commented
@cienvaras Thank you! This is ready for review!

2024-06-14 02:44 UTC, cienvaras approved these changes
Works great, thanks! 🚀

2024-06-14 02:44 UTC, merged