Shs 5621 misc fixes and improvements
SU-HSDO/suhumsci pull request #1551
Opened 2024-06-10 18:38 UTC by mariannuar

# READY FOR REVIEW

## Summary
_[briefly summarize the changes here]_

## Need Review By (Date)
_['10/30', 'asap', etc.]_

## Urgency
_['low', 'medium', 'high', etc.]_

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-06-13 03:02 UTC, cienvaras requested changes
@mariannuar Looks good, just some minor changes needed. Let me know if you have questions.

Also updated the branch here to add the "Theme assets compile" code.

2024-06-13 03:02 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.general.scss
> -  @include pseudo-background-box($color, $height, $width);
I think it's a good idea to add the same defaults that `hb-colorful-text-bar` had here, to avoid repetition when using this mixin. Also fix existing uses of the mixins to remove the extra variables.

2024-06-13 03:02 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.buttons.scss
> -        background-color: transparent;
This `background-color` on hover is needed. Also need to add back the `transparent` color for other border sides. Check the reset button on [this page](https://history.stanford.edu/events/upcoming-events) to see the effect of these rules.

2024-06-13 03:02 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.general.scss
> +@mixin hb-base-list {
I think I made a mistake here, actually having an extra mixin makes things more complicated as there are multiple places to set rules. Also, there aren't many shared rules, so there's no really a benefit. Please revert to previous state, sorry :/

2024-06-13 19:25 UTC, mariannuar commented
@cienvaras Thank you! This is ready for review again!

2024-06-14 02:36 UTC, cienvaras approved these changes
@mariannuar Thanks a lot for the work! After some thought, I ended up restoring `hb-colorful-text-bar` mixin. It had some very specific width and height values that didn't work well with `pseudo-background-box`. Removing it could affect the developer experience. Sorry (and thanks!) for the extra work 😅

2024-06-14 02:36 UTC, merged

2024-06-26 20:09 UTC, cienvaras reviewed
🚀