SHS-5629: Editors can more easily edit a caption
SU-HSDO/suhumsci pull request #1580
Opened 2024-07-19 19:01 UTC by codechefmarc

# READY FOR REVIEW

## Summary
_[briefly summarize the changes here]_

## Need Review By (Date)
_['10/30', 'asap', etc.]_

## Urgency
_['low', 'medium', 'high', etc.]_

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-07-25 03:50 UTC, cienvaras requested changes
@codechefmarc I can see the edit button and open the modal, but I found an issue with the modal position. It's not always centered, and sometimes the "Save" button cannot be accessed:
<img width="1477" alt="Screenshot 2024-07-24 at 9 45 49 PM" src="https://github.com/user-attachments/assets/f260e63c-5b17-4e65-9aaa-46a3cae18946">

Not sure what's the cause of the issue, because every other time the modal is rendered in the right position.

Also, please check the other comment I left in the code. Thanks!

2024-07-25 03:50 UTC, cienvaras commented on composer.json
> +                "Allow media items to be edited in a modal when using the field widget https://www.drupal.org/project/drupal/issues/2985168": "patches/2985168-172.patch"
@codechefmarc Can you change this to pull the patch directly from drupal.org instead of downloading it and using a local copy, please? That's the standard practice in this project, we only use local patches if it's something that's not in the issue queue. Thanks!

2024-07-25 22:09 UTC, codechefmarc commented on composer.json
> +                "Allow media items to be edited in a modal when using the field widget https://www.drupal.org/project/drupal/issues/2985168": "patches/2985168-172.patch"
Fixed!

2024-07-25 22:10 UTC, codechefmarc commented
@cienvaras - Ok, switched out the patch for a d.o. version and also added a patch that I think fixes the save button issue. It had to do with Gin, I believe. I had a hard time recreating as it worked for me without that patch, but once I put that patch in, it works all the time, I think? Please re-test. What browser were you using? I tested on Arc and Safari.

2024-07-26 16:35 UTC, cienvaras commented
@codechefmarc I initially tested in Arc in Mac. After applying the gin patch, I tested again in Arc, Chrome and Safari and I still have the issue in Arc and Chrome, Safari works well.

It seems that the issue is related to scrolling. In most cases, the dialog is initially shown in the right position, but if I close it, scroll the page and open it again it's displayed too low on the page.

I'll try to get someone else to test this and discard that the problem is happening only on my computer, but I'll hold on merging this until we're sure that the issue is solved.

2024-07-26 21:49 UTC, ahughes3 commented
> It seems that the issue is related to scrolling. In most cases, the dialog is initially shown in the right position, but if I close it, scroll the page and open it again it's displayed too low on the page.
> 
> I'll try to get someone else to test this and discard that the problem is happening only on my computer, but I'll hold on merging this until we're sure that the issue is solved.

@codechefmarc @cienvaras  I tested today using Chrome on a Mac and the issue is still there. I tested previously before the patch was added and experienced the same issue. The modal opens up but I can't scroll to access the save button

https://www.loom.com/share/cef1a182ef7745c1988cb31241851c8e?sid=ee07a8e6-f092-4577-812b-c98fefe0eee9

2024-07-29 16:10 UTC, codechefmarc commented
@ahughes3 , @cienvaras  - Thank you for testing, I'll get back on this ticket and research how we can fix that odd bug. I'm sure there is a way.

2024-07-30 17:18 UTC, codechefmarc commented
@ahughes3 and @cienvaras  - I pushed some changes up and tested the dialog after scrolling and it appear to be working for me, please re-test. Thank you!
https://pr1580-lqaarerjbqqcvxksaxnggcqcjx0lz4qh.tugboatqa.com/

2024-08-09 21:27 UTC, merged