SHS-5781: Regression: Color contrast issue on Warbler "load more" links
SU-HSDO/suhumsci pull request #1601
Opened 2024-08-14 20:34 UTC by mariannuar

# READY FOR REVIEW

## Summary
 Fix regression color contrast issue on Warbler "load more" links

## Need Review By (Date)
08/23

## Urgency
medium

## Steps to Test
1. Change the `Color Pairing` to `Warbler`
2. Go to the following sites and pages:

- https://english.suhumsci.loc/research/british-literature (and other research areas on the English site)
- https://mcs.suhumsci.loc/events-news/news-archive (and other news archive pages on MCS)

3. Check the "load more" looks as expected in all states (normal, hover, focus)

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-08-14 20:37 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1601-rm5avbd93a8yu4lgn5brx3aninlxn2up.tugboatqa.com
- https://hs-colorful-rm5avbd93a8yu4lgn5brx3aninlxn2up.tugboatqa.com
- https://hs-traditional-rm5avbd93a8yu4lgn5brx3aninlxn2up.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66bd14cb6c7d83449c0271f8

2024-08-19 21:15 UTC, cienvaras requested changes
@mariannuar works great, just found a minor possible improvement, please check the inline comments.

2024-08-19 21:15 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/components/_pager.scss
> +        .hs-button,
Works and look good. Just a small detail to be on the safe side: can you please update a selector to include the case when the `<a>` is inside another element with the button classes? Something like this:

```
.hs-button, .hs-button a,
.hs-button--big, .hs-button--big a,
...
```

I don't think this is being used in any site right now, but it's a valid pattern for buttons and it's better to build the styles as bulletproof as possible.

2024-08-20 19:13 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1601-rm5avbd93a8yu4lgn5brx3aninlxn2up.tugboatqa.com
- https://hs-colorful-rm5avbd93a8yu4lgn5brx3aninlxn2up.tugboatqa.com
- https://hs-traditional-rm5avbd93a8yu4lgn5brx3aninlxn2up.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66bd14cb6c7d83449c0271f8

2024-08-20 19:22 UTC, mariannuar commented
@cienvaras Updated! I tested it like this and it's working

![Screenshot 2024-08-20 at 1 21 49 PM](https://github.com/user-attachments/assets/0b4d2864-aa33-4eba-868e-3377f2b8b6aa)

2024-08-21 02:51 UTC, cienvaras approved these changes
LGTM, thanks for the fix!

2024-08-21 02:52 UTC, merged