feat(shs-5777): new approach to multi select exposed filter
SU-HSDO/suhumsci pull request #1603
Opened 2024-08-19 16:39 UTC by mariannuar

# READY FOR REVIEW

## Summary
_[briefly summarize the changes here]_

## Need Review By (Date)
_['10/30', 'asap', etc.]_

## Urgency
_['low', 'medium', 'high', etc.]_

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-08-20 03:53 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1603-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-colorful-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-traditional-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66c4127f5806033293f9a714

2024-08-20 18:44 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1603-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-colorful-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-traditional-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66c4127f5806033293f9a714

2024-08-20 19:01 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1603-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-colorful-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-traditional-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66c4127f5806033293f9a714

2024-08-22 17:51 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1603-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-colorful-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-traditional-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66c4127f5806033293f9a714

2024-08-22 18:10 UTC, cienvaras requested changes
@mariannuar Looks really good, but there are a couple of things to fix. I found a minor issue with formatting (see inline comment) and also a bug: When I click outside of the select, the element doesn't close, I have to click twice. And, on top of that there's some weird behavior with the "All" option:
- Open the select and click on "All". Click outside to close the element
- Open the select again and click on "All" again. Checkboxes should clear
- Click outside to close the select. All elements are shown as selected (bug)
- Click outside again to finally close the select. You can see that "Choose one or more options" is displayed, meaning that the checkboxes were correctly unselected

Please see the loom video and let me know if you have any questions

https://www.loom.com/share/001bbef6a059462d875541664c4699c4?sid=b67fccae-896b-4910-9178-c3586bfea041

2024-08-22 18:10 UTC, cienvaras commented on docroot/profiles/humsci/su_humsci_profile/js/select-lists/src/select-list-filters.island.tsx
> -import {createIslandWebComponent} from 'preact-island'
@mariannuar Lots of these changes are due to automatic formatting. While it's good to standardize things, I think there's no prettier config file in this folder and you're using some default standards that don't match the standards we have in the rest of the site (like using double instead of single quotes). To fix this, please add a `.prettierrc` file in `docroot/profiles/humsci/su_humsci_profile/js/select-lists/` with the following content:

```json
{
  "printWidth": 80,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "all"
}
```

2024-08-22 18:26 UTC, cienvaras commented
@mariannuar Also, please take a look a the Code Climate errors.

2024-08-22 19:02 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1603-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-colorful-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-traditional-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66c4127f5806033293f9a714

2024-08-26 21:17 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1603-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-colorful-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-traditional-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66c4127f5806033293f9a714

2024-08-26 21:58 UTC, mariannuar commented
@cienvaras This is ready for review again!

2024-08-26 22:02 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1603-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-colorful-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-traditional-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66c4127f5806033293f9a714

2024-09-03 15:08 UTC, cienvaras approved these changes
@mariannuar Works as expected, thanks for the fixes!

@ahughes3 This is ready for you to review.

2024-09-03 15:10 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1603-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-colorful-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com
- https://hs-traditional-wbsurcyqzshj3s6kqccmslagj1c1yn6u.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66c4127f5806033293f9a714

Visual Diffs:
- https://dashboard.tugboatqa.com/66c4127f5806033293f9a714/visualdiffs

2024-09-04 17:57 UTC, ahughes3 approved these changes
Works as expected and looks good, approved by H&S

2024-09-04 19:01 UTC, joegl approved these changes

2024-09-04 19:08 UTC, merged