SHS-5784: New Well Color for Collections: Front-end
SU-HSDO/suhumsci pull request #1616
Opened 2024-09-03 23:41 UTC by mariannuar

# READY FOR REVIEW

## Summary
Update the styles and logic to make the new two fields `Background Color (field_bg_color)` and `Background Color Width (field_bg_color_width)` work in the FE

## Need Review By (Date)
09/04

## Urgency
medium

## Steps to Test
1. On Traditional and Colorful
2. Create a `Flexible Page` and add `Collections` for each `Background Color` and each `Background Color Width`
3. Verify the width is correct and the color for all of them look like what it's proposed in the design ([Traditional](https://www.figma.com/design/hOtD5MStjFIavUrWapHKHN/UX%2FDesign-Tickets-Work?node-id=1532-5054&t=3gjoZR6wiJhj7ah4-4) / [Colorful](https://www.figma.com/design/hOtD5MStjFIavUrWapHKHN/UX%2FDesign-Tickets-Work?node-id=1532-8341&t=3gjoZR6wiJhj7ah4-4)). The distribution of the colors in the design it's in the following way:

- Color default value -> Colors in the first column (left side of the page)
- Grey -> Color in the second column (center of the page)
- Light -> Colors in the last column (right side of the page)

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-09-03 23:44 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1616-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com
- https://hs-colorful-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com
- https://hs-traditional-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66d79e91de20cce38fbed76a

Visual Diffs:
- https://dashboard.tugboatqa.com/66d79e91de20cce38fbed76a/visualdiffs

2024-09-03 23:55 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1616-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com
- https://hs-colorful-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com
- https://hs-traditional-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66d79e91de20cce38fbed76a

Visual Diffs:
- https://dashboard.tugboatqa.com/66d79e91de20cce38fbed76a/visualdiffs

2024-09-04 00:01 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1616-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com
- https://hs-colorful-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com
- https://hs-traditional-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66d79e91de20cce38fbed76a

Visual Diffs:
- https://dashboard.tugboatqa.com/66d79e91de20cce38fbed76a/visualdiffs

2024-09-04 23:28 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1616-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com
- https://hs-colorful-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com
- https://hs-traditional-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66d79e91de20cce38fbed76a

Visual Diffs:
- https://dashboard.tugboatqa.com/66d79e91de20cce38fbed76a/visualdiffs

2024-09-05 00:39 UTC, cienvaras requested changes
@mariannuar Works as expected. However, we need to define a color for `vireo` pairing and also do a couple of improvements in the code. Please check the inline comments.

2024-09-05 00:39 UTC, cienvaras commented on docroot/modules/humsci/hs_paragraph_types/hs_paragraph_types.module
> +      $bg_color = str_replace('_', '-', $paragraph->get('field_bg_color')->getString());
Please use `Html::cleanCssIdentifier()` instead of `str_replace()` to clean the string for use as part a class.

2024-09-05 00:39 UTC, cienvaras commented on docroot/modules/humsci/hs_paragraph_types/hs_paragraph_types.module
> +        $variables['attributes']['class'][] = 'hs-paragraph-style hs-paragraph-style--' . $bg_width_class . ' hs-paragraph-style--' . $bg_color;
It's not ideal to have multiple classes in the same entry of the `class` array, please add them separately. Please fix for the private collections as well (You can add the `hs-paragraph-style` class outside of the `if`, as it applies for both bundles).

```
        $variables['attributes']['class'][] = 'hs-paragraph-style;
        $variables['attributes']['class'][] = 'hs-paragraph-style--' . $bg_width_class;
        $variables['attributes']['class'][] = 'hs-paragraph-style--' . $bg_color;
```

2024-09-05 00:39 UTC, cienvaras commented on docroot/modules/humsci/hs_paragraph_types/hs_paragraph_types.module
> +  if (in_array($bundle, ['hs_collection', 'hs_priv_collection'])) {
To reduce nesting, try to use early returns in the `if`'s. For example:

```
if (!in_array($bundle, ['hs_collection', 'hs_priv_collection'])) {
  return NULL;
}
...
```

2024-09-05 00:39 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/settings/_variables.traditional-pairings.scss
>    'vireo': (
I know it wasn't in the designs, but we need to define colors for the new `vireo` pairing. Please check with Katy to choose the color.

2024-09-05 17:44 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1616-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com
- https://hs-colorful-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com
- https://hs-traditional-91a52pchzdktwenvhcennatqscbeqci3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66d79e91de20cce38fbed76a

Visual Diffs:
- https://dashboard.tugboatqa.com/66d79e91de20cce38fbed76a/visualdiffs

2024-09-05 18:17 UTC, mariannuar commented
@cienvaras Thank you!! This is ready for review again!

2024-09-10 17:43 UTC, cienvaras approved these changes
@mariannuar Looks great, thanks for the fixes!

@ahughes3 Ready for you to review.

2024-09-10 17:45 UTC, merged