SHS-5779): Implementation: Testimonial Update
SU-HSDO/suhumsci pull request #1628
Opened 2024-09-19 22:04 UTC by mariannuar

# READY FOR REVIEW

## Summary
New design for Testimonial when it's used in a Collection

## Need Review By (Date)
09/24

## Urgency
medium

## Steps to Test
1. Go to this page `/components/testimonials` in Colorful and Traditional
2. Verify the `Testimonial` component still looks the same when it's not being used in `Collections`
3. When the `Testimonial` component is being used in `Collections`, it looks according to the new [design]( https://www.figma.com/design/hOtD5MStjFIavUrWapHKHN/UX%2FDesign-Tickets-Work?node-id=1900-2180&t=fXFnahJTU4zxg1a1-4) in both themes
4. Please test all the colour palette of the site

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-09-19 22:07 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1628-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-colorful-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-traditional-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde

Visual Diffs:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde/visualdiffs

2024-09-19 22:19 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1628-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-colorful-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-traditional-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde

Visual Diffs:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde/visualdiffs

2024-09-23 18:36 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1628-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-colorful-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-traditional-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde

Visual Diffs:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde/visualdiffs

2024-09-23 18:51 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1628-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-colorful-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-traditional-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde

Visual Diffs:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde/visualdiffs

2024-09-23 18:54 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1628-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-colorful-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-traditional-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde

Visual Diffs:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde/visualdiffs

2024-09-23 19:09 UTC, mariannuar commented
@cienvaras This is ready for review again! :)

2024-09-23 20:50 UTC, ahughes3 commented
@mariannuar @cienvaras I received feedback from Tori and the font style isn't up to date in figma and the font should not be italicized, Tori is also going to add an update to the ticket in clickup

2024-09-23 21:22 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1628-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-colorful-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-traditional-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde

Visual Diffs:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde/visualdiffs

2024-09-23 22:24 UTC, cienvaras requested changes
@mariannuar Besides the font changes, I found an issue in collections with raised cards:

<img width="525" alt="Screenshot 2024-09-23 at 4 04 01 PM" src="https://github.com/user-attachments/assets/b778e682-9cc0-40b9-b209-88e028446d8a">

There's an extra space between the card border and the new border in the testimonial that shouldn't be there according to the designs.

I also left a couple of comments in the code to fix minor issues. Other than that it's looking good, thanks!

2024-09-23 22:24 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/components/_pattern.testimonial.scss
> +
Please avoid adding lines with just spaces. This can be prevented setting auto formatting with prettier in your editor.

2024-09-23 22:24 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/components/_pattern.testimonial.scss
> +      &,
Using a single `&` can be a bit confusing when the parent block has a lot of rules and other nested selectors. It's better to duplicate the rule to make the code easier to read (it won't affect the resulting CSS). Please limit its use to cases when the parent selector is close and the structure is obvious.

2024-09-23 22:55 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1628-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-colorful-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-traditional-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde

Visual Diffs:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde/visualdiffs

2024-09-23 23:08 UTC, mariannuar commented
@cienvaras Thank you! This is ready for review again. Fonts are updated too.

2024-09-24 14:38 UTC, cienvaras approved these changes
@mariannuar Thanks for the fixes, it look good!

@ahughes3 Ready for you.

2024-09-24 18:34 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1628-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-colorful-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com
- https://hs-traditional-iiqcxuj1ays5io9gat2tensgzw3b7xse.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde

Visual Diffs:
- https://dashboard.tugboatqa.com/66ec9ffbd1f73e98941b9fde/visualdiffs

2024-09-25 17:11 UTC, ahughes3 approved these changes
Looks good!

2024-09-25 22:15 UTC, joegl approved these changes

2024-09-26 16:49 UTC, ahughes3 commented
@cienvaras @joegl Checking in on this one, I see it was approved but merging is blocked

2024-09-26 17:14 UTC, joegl commented
> @cienvaras @joegl Checking in on this one, I see it was approved but merging is blocked

I'm working on getting the tests to pass. They just passed and I will be merging now 👍

2024-09-26 17:15 UTC, merged