SHS-5796: Remove colorful's half-background link style, use trad's style instead
SU-HSDO/suhumsci pull request #1671
Opened 2024-10-29 23:10 UTC by mariannuar

# READY FOR REVIEW

## Summary
Remove colorful's half-background link style and use traditional style instead

## Need Review By (Date)
11/05

## Urgency
medium

## Steps to Test
1. Visit https://hs-colorful.suhumsci.loc/components/text-area-typography 
2. Hover any kind of link and confirm that they don't have the half-background style anymore. They should look similar to the ones in the traditional theme

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-10-29 23:21 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1671-ycq1d7e1inzqa0ydu1lcdisx0hwtspbq.tugboatqa.com
- https://hs-colorful-ycq1d7e1inzqa0ydu1lcdisx0hwtspbq.tugboatqa.com
- https://hs-traditional-ycq1d7e1inzqa0ydu1lcdisx0hwtspbq.tugboatqa.com
- https://english-ycq1d7e1inzqa0ydu1lcdisx0hwtspbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67216b5a3e2dd2b98c32436e

Visual Diffs:
- https://dashboard.tugboatqa.com/67216b5a3e2dd2b98c32436e/visualdiffs

2024-11-01 23:30 UTC, cienvaras requested changes
@mariannuar Looks good, but I think you're missing some links, for example the card titles:

<img width="576" alt="Screenshot 2024-11-01 at 5 29 34 PM" src="https://github.com/user-attachments/assets/be127299-cf43-44dd-902e-7fe17b30330e">

Please do a general inspection on all components, to confirm that all links with the half-background have been fixed and that there are no undesired effects.

2024-11-01 23:30 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.links.scss
> -    @include hb-link-background-image($icon, $icon-width, $icon-position);
I'm pretty sure you're removing all uses of this mixin, you can remove altogether.

2024-11-04 20:46 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1671-ycq1d7e1inzqa0ydu1lcdisx0hwtspbq.tugboatqa.com
- https://hs-colorful-ycq1d7e1inzqa0ydu1lcdisx0hwtspbq.tugboatqa.com
- https://hs-traditional-ycq1d7e1inzqa0ydu1lcdisx0hwtspbq.tugboatqa.com
- https://english-ycq1d7e1inzqa0ydu1lcdisx0hwtspbq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67216b5a3e2dd2b98c32436e

Visual Diffs:
- https://dashboard.tugboatqa.com/67216b5a3e2dd2b98c32436e/visualdiffs

2024-11-04 21:04 UTC, mariannuar commented
@cienvaras Ready for review again. Please go to https://hs-colorful-ycq1d7e1inzqa0ydu1lcdisx0hwtspbq.tugboatqa.com/components/collections/collections-postcards/vertical-cards and https://hs-colorful-ycq1d7e1inzqa0ydu1lcdisx0hwtspbq.tugboatqa.com/default-views/news

2024-11-06 03:55 UTC, ahughes3 approved these changes
Looks good on our end!

2024-11-06 17:05 UTC, cienvaras commented
@ahughes3 LGTM too! I'll assign it to Joe.

2024-11-06 17:06 UTC, cienvaras approved these changes
@mariannuar Looks great, thanks!

2024-11-06 17:58 UTC, joegl approved these changes

2024-11-06 17:59 UTC, merged