SHS-5911: Indicator of shortcut menu 3rd level
SU-HSDO/suhumsci pull request #1681
Opened 2024-11-07 00:12 UTC by mariannuar

# READY FOR REVIEW

## Summary
Adds indicator of shortcut menu 3rd level

## Need Review By (Date)
11/20

## Urgency
'medium

## Steps to Test
1. Visit the shortcut menu
2. In the Site Actions menu item, check that the menu item "Page not found" has an indicator that let's the user know there's a third level menu item

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-11-07 20:14 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1681-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com
- https://hs-colorful-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com
- https://hs-traditional-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com
- https://english-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com
- https://history-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com
- https://west-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672d1b7321db79eb2362c31f

2024-11-13 17:10 UTC, cienvaras requested changes
@mariannuar Looks great, but the indicator is only present on the FE theme. If I visit an admin page (e.g. `/admin/content`) the indicator is absent. You need to also add the styles in the admin theme.

2024-11-13 20:44 UTC, mariannuar commented
@cienvaras Ready for review again. Visit https://pr1681-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com/ and check for Shortcuts > Site Actions > Page not found Report > Third level

2024-11-14 02:12 UTC, cienvaras requested changes
@mariannuar Left a question for you.

2024-11-14 02:12 UTC, cienvaras commented on docroot/themes/humsci/su_humsci_gin_admin/dist/su_humsci_gin_admin.css
> +#toolbar-item-shortcuts-tray li > ul li.has-submenu > a::after {
Why not `li:has(.menu)` instead of adding a class with JS? I did a quick test with the dev tools and it works, but I might be missing something.

2024-11-14 18:05 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1681-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com
- https://hs-colorful-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com
- https://hs-traditional-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com
- https://english-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com
- https://history-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com
- https://west-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672d1b7321db79eb2362c31f

2024-11-14 18:10 UTC, mariannuar commented
@cienvaras Back to you. https://hs-colorful-drxb2zpp0vmpul1acmcab6mkcz95fral.tugboatqa.com/

2024-11-14 21:31 UTC, cienvaras commented
@mariannuar LGTM! 🚀 

@ahughes3 Ready for your review.

2024-11-14 21:33 UTC, cienvaras approved these changes

2024-11-18 16:44 UTC, ahughes3 approved these changes
LGTM!

2024-11-19 19:01 UTC, mariannuar commented
Hi @joegl can we please hold on the merge of this PR? My local environment is not working right now, and I would like to use the tugboat preview of this PR for today's demo. Thanks!

2024-11-19 20:17 UTC, joegl commented
> Hi @joegl can we please hold on the merge of this PR? My local environment is not working right now, and I would like to use the tugboat preview of this PR for today's demo. Thanks!

No problem @mariannuar ! Let me know once it's ready again and hope the demo goes great 👍

2024-11-19 20:25 UTC, mariannuar commented
@joegl Thank you! It's ready again. 🙂

2024-11-22 15:36 UTC, joegl approved these changes

2024-11-22 15:36 UTC, merged