SHS-5963: FE performance refactor theme javascript
SU-HSDO/suhumsci pull request #1691
Opened 2024-11-25 23:59 UTC by mariannuar

# READY FOR REVIEW

## Summary
_[briefly summarize the changes here]_

## Need Review By (Date)
_['10/30', 'asap', etc.]_

## Urgency
_['low', 'medium', 'high', etc.]_

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-11-26 17:32 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-colorful-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-traditional-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://english-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://history-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://west-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6745ffd3513b09d01cb99f79

2024-11-27 16:56 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-colorful-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-traditional-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://english-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://history-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://west-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6745ffd3513b09d01cb99f79

2024-11-27 17:26 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-colorful-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-traditional-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://english-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://history-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://west-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6745ffd3513b09d01cb99f79

2024-11-27 20:30 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-colorful-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-traditional-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://english-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://history-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://west-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6745ffd3513b09d01cb99f79

2024-11-27 20:59 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-colorful-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-traditional-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://english-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://history-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://west-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6745ffd3513b09d01cb99f79

2024-11-28 20:52 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-colorful-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-traditional-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://english-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://history-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://west-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6745ffd3513b09d01cb99f79

2024-11-28 23:37 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-colorful-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-traditional-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://english-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://history-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://west-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6745ffd3513b09d01cb99f79

2024-11-29 23:37 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-colorful-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-traditional-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://english-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://history-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://west-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6745ffd3513b09d01cb99f79

2024-11-30 00:50 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-colorful-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-traditional-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://english-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://history-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://west-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6745ffd3513b09d01cb99f79

2024-11-30 01:28 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-colorful-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-traditional-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://english-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://history-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://west-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6745ffd3513b09d01cb99f79

2024-12-02 17:23 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-colorful-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://hs-traditional-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://english-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://history-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com
- https://west-lcef6m3ifgds4nk73jfeejs0mejt5nta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6745ffd3513b09d01cb99f79

2024-12-04 21:48 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-04 22:55 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-05 01:04 UTC, cienvaras requested changes
@mariannuar Almost there, but still some work needed:
- `vertical-tabs.js` is being loaded in all pages that use layout builder, not only in the form
- The WYSIWYG related scripts are not being loaded in all cases
- Most scripts should use the `once` library to prevent multiple executions on AJAX calls
- The table related scripts are being loaded in all views, not only when a table is used
- Handle photo gallery scripts using template instead of preprocess

2024-12-05 01:14 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-06 00:19 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-10 01:04 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-10 19:03 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-10 22:29 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-10 23:06 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-11 16:07 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-11 16:31 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-11 16:54 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-11 17:07 UTC, mariannuar commented
@cienvaras Ready for review again!

2024-12-20 17:39 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-20 18:05 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-20 23:27 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2024-12-20 23:29 UTC, cienvaras approved these changes
@mariannuar Good work, thanks for all the fixes, it was a complicated ticket. I added some extra fixes, we can review them when we come back from the break.

@ahughes3 This one is ready for you to review next year! I was a big refactor, but there shouldn't be any content, visual or behavior change, it was a low level update on how JS code is organized and loaded. I did a thoroughly review before approving the PR and confirmed that all changes work as expected. Mari added instructions on how to change each feature, but if you want to do a quick review you can visit some representative pages and test the interactive elements.

2025-01-06 17:42 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2025-01-13 19:39 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2025-01-23 19:11 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2025-01-24 01:11 UTC, ahughes3 approved these changes
approved!

2025-01-27 17:38 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2025-01-27 21:32 UTC, joegl requested changes
LGTM just one suggestion:

Because the `humsci_basic` theme is now including templates from the `hs_layouts` module there should be a dependency added for it in the `humsci_basic.info.yml`.

```
dependencies:
  - hs_layouts:hs_layouts
```

2025-02-03 17:48 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2025-02-03 18:08 UTC, cienvaras commented
@joegl Good catch, thanks! I just added the missing dependency.

2025-02-10 17:47 UTC, ahughes3 commented
@joegl @cienvaras Is there anything additional that's needed in order to get this one reviewed and merged?

2025-02-10 18:10 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2025-02-10 18:31 UTC, cienvaras commented
@ahughes3 @joegl I just pulled the new release branch and fixed some conflicts, it's ready to go on our side.

2025-02-10 18:35 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1691-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-colorful-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://hs-traditional-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://english-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://history-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com
- https://west-yjaw12j2elpdkv3tainq9lof6up2zgx4.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c

Visual Diffs:
- https://dashboard.tugboatqa.com/674dfa21b8d4abaca99d0b9c/visualdiffs

2025-02-10 21:24 UTC, joegl approved these changes

2025-02-10 21:25 UTC, merged