SH-5972: Use default Drupal layouts in Dashboard
SU-HSDO/suhumsci pull request #1697
Opened 2024-12-12 22:21 UTC by mariannuar

# READY FOR REVIEW

## Summary
Update logic in hs_layouts.module to use default Drupal layouts in Dashboards instead of the onces used in the FE

## Urgency
medium

## Steps to Test
1. Go to
2. Edit layout
3. Add a section and confirm there are only four layouts (1 Col, 2 Cols, 3 Cols, 4 Cols) that can be used in Dasboard
4. Add any of them and confirm they look good (there will another ticket to make it looks better, once there's a design)
5. Go to any page in the site (for example /accordions/accordions-secondary)
6. Confirm the same custom layouts can be used and not the default by Drupal

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-12-12 22:27 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1697-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://hs-colorful-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://hs-traditional-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://english-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://history-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://west-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/675b6209252c7a7b92288852

Visual Diffs:
- https://dashboard.tugboatqa.com/675b6209252c7a7b92288852/visualdiffs

2024-12-14 00:38 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1697-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://hs-colorful-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://hs-traditional-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://english-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://history-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://west-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/675b6209252c7a7b92288852

Visual Diffs:
- https://dashboard.tugboatqa.com/675b6209252c7a7b92288852/visualdiffs

2024-12-16 04:09 UTC, cienvaras requested changes
@mariannuar That's a good start, just added some notes for doing the implementation more robust and clear.

2024-12-16 04:09 UTC, cienvaras commented on docroot/modules/humsci/hs_layouts/hs_layouts.module
> +  $active_theme = \Drupal::theme()->getActiveTheme()->getName();
I was checking and there's a more robust way to test if we're in the Dashboard. `$extra` includes a `section_storage` element that will be an instance of `Drupal\dashboard\Plugin\SectionStorage\DashboardSectionStorage` if the current layout builder instance is a dashboard.

Also, having all conditions in a single `if` is a bit confusing. I'd change it to something like this:

```
if ($extra['section_storage'] instanceof DashboardSectionStorage) {
  // Logic for filtering the sections that will be available for the dashboard.
}
else {
  // Logic for keeping only the sections defined in the `hs_layout` module.
}
```

Also:
- Make sure to add `use Drupal\dashboard\Plugin\SectionStorage\DashboardSectionStorage;` in the top of the file.
- Add the dashboard module as a dependency for `hs_layouts` in the `info.yml` file

2024-12-16 20:54 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1697-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://hs-colorful-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://hs-traditional-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://english-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://history-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://west-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/675b6209252c7a7b92288852

Visual Diffs:
- https://dashboard.tugboatqa.com/675b6209252c7a7b92288852/visualdiffs

2024-12-17 17:09 UTC, cienvaras requested changes
@mariannuar Almost there, just a couple of things to fix.

2024-12-17 17:09 UTC, cienvaras commented on docroot/modules/humsci/hs_layouts/hs_layouts.info.yml
> +  - drupal/dashboard
This is not the right format for dependencies. See https://www.drupal.org/docs/develop/theming-drupal/defining-a-theme-with-an-infoyml-file#dependencies

```suggestion
  - dashboard:dashboard
```

2024-12-17 17:09 UTC, cienvaras commented on docroot/modules/humsci/hs_layouts/hs_layouts.module
> +use Drupal\dashboard\Plugin\SectionStorage\DashboardSectionStorage;
`use` statements should be sorted alphabetically.

2024-12-17 17:09 UTC, cienvaras commented on docroot/modules/humsci/hs_layouts/hs_layouts.module
> +      // Define providers to unset for the gin admin theme.
```suggestion
      // Define providers to unset for the dashboard.
```

2024-12-17 17:09 UTC, cienvaras commented on docroot/modules/humsci/hs_layouts/hs_layouts.module
> +      $admin_providers_to_unset = [
Try to keep variable names under 20 char, otherwise we'll get a CodeClimate error.

2024-12-17 17:28 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1697-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://hs-colorful-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://hs-traditional-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://english-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://history-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://west-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/675b6209252c7a7b92288852

Visual Diffs:
- https://dashboard.tugboatqa.com/675b6209252c7a7b92288852/visualdiffs

2024-12-17 17:36 UTC, mariannuar commented
@cienvaras Done!

2024-12-17 17:36 UTC, mariannuar commented on docroot/modules/humsci/hs_layouts/hs_layouts.info.yml
> +  - drupal/dashboard
Oh 👀 thanks!

2024-12-17 17:56 UTC, cienvaras requested changes
@mariannuar Only one change needed.

2024-12-17 17:56 UTC, cienvaras commented on docroot/modules/humsci/hs_layouts/hs_layouts.info.yml
> +  - drupal:dashboard
For contrib modules you should add the module name twice. `drupal:something` is only for core modules.

```suggestion
  - dashboard:dashboard
```

2024-12-17 18:05 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1697-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://hs-colorful-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://hs-traditional-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://english-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://history-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com
- https://west-pksvk1y2mlhnkwglqkecukewc9y0oft0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/675b6209252c7a7b92288852

Visual Diffs:
- https://dashboard.tugboatqa.com/675b6209252c7a7b92288852/visualdiffs

2024-12-17 19:25 UTC, cienvaras approved these changes
@mariannuar Thanks, looks good. Merging into the longterm dashboard branch.

2024-12-17 19:26 UTC, merged