SHS-5944: Uninstall Honeypot module
SU-HSDO/suhumsci pull request #1698
Opened 2024-12-14 00:35 UTC by codechefmarc

# READY FOR REVIEW

## Summary
- Removes configuration for and uninstalls Honeypot module

## Need Review By (Date)
2024-12-18

## Urgency
low

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-12-14 00:43 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1698-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://hs-colorful-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://hs-traditional-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://english-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://history-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://west-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/675cd2e2919fa9b3e70581e2

Visual Diffs:
- https://dashboard.tugboatqa.com/675cd2e2919fa9b3e70581e2/visualdiffs

2024-12-16 19:00 UTC, dalin- reviewed
@codechefmarc 
I took a look at a tugboat site, and the module/config is all gone (as expected).  I was hoping to be able to look at a log somewhere and see the `Deleted @config` messages, but I couldn't find that in either Tugboat or Github Actions.  

Maybe I'm not the best person to review this :-)

2024-12-16 21:05 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1698-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://hs-colorful-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://hs-traditional-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://english-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://history-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://west-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/675cd2e2919fa9b3e70581e2

Visual Diffs:
- https://dashboard.tugboatqa.com/675cd2e2919fa9b3e70581e2/visualdiffs

2024-12-17 17:23 UTC, cienvaras requested changes
@codechefmarc Works as expected. There's one thing you missed though: please remove the module dependency in `docroot/profiles/humsci/su_humsci_profile/su_humsci_profile.info.yml`.

2024-12-18 23:51 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1698-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://hs-colorful-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://hs-traditional-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://english-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://history-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://west-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/675cd2e2919fa9b3e70581e2

Visual Diffs:
- https://dashboard.tugboatqa.com/675cd2e2919fa9b3e70581e2/visualdiffs

2024-12-19 00:01 UTC, codechefmarc commented
@cienvaras - Good catch. Removed.

2024-12-19 17:57 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1698-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://hs-colorful-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://hs-traditional-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://english-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://history-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://west-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/675cd2e2919fa9b3e70581e2

Visual Diffs:
- https://dashboard.tugboatqa.com/675cd2e2919fa9b3e70581e2/visualdiffs

2024-12-19 19:15 UTC, cienvaras approved these changes
@codechefmarc LGTM, thanks for the fix!

@ahughes3 Ready for you to review.

2025-01-06 15:43 UTC, ahughes3 commented
@cienvaras The module is still listed at `/admin/modules` but is not checked, this is the expected outcome from this PR correct? 

![image](https://github.com/user-attachments/assets/6e2248d0-5602-4e79-a951-260c2065ca8c)

2025-01-06 15:49 UTC, cienvaras commented
@ahughes3 Correct. This PR only uninstalls the module, full module removal should be done in a separate PR on the next release.

2025-01-06 17:42 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1698-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://hs-colorful-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://hs-traditional-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://english-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://history-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com
- https://west-tdjamz0jt7aaofcqqiqhxxhqret0wqpl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/675cd2e2919fa9b3e70581e2

Visual Diffs:
- https://dashboard.tugboatqa.com/675cd2e2919fa9b3e70581e2/visualdiffs

2025-01-08 19:54 UTC, ahughes3 approved these changes
Looks good!

2025-01-08 21:20 UTC, pookmish requested changes

2025-01-08 21:20 UTC, pookmish commented on docroot/profiles/humsci/su_humsci_profile/su_humsci_profile.install
> +
Actually, this isn't required. those configs have a dependency on the module, so disabling the module removes the configs automatically.

2025-01-09 17:08 UTC, ahughes3 commented on docroot/profiles/humsci/su_humsci_profile/su_humsci_profile.install
> +
@codechefmarc

2025-01-10 18:34 UTC, codechefmarc commented
@pookmish - thank you for the comments, I've combined these two PRs into one, here: https://github.com/SU-HSDO/suhumsci/pull/1713

2025-01-10 18:34 UTC, closed without merging