SHS-5996/SHS-5997: WYSIWYG link styles with arrow or external-link show green icon instead of matching the colour palette / WYSIWYG link style "External Link" does not show external icon
SU-HSDO/suhumsci pull request #1703
Opened 2024-12-19 00:59 UTC by mariannuar

# READY FOR REVIEW

## Summary
- WYSIWYG link styles with arrow or external-link icon color matches the colour palette
- WYSIWYG link style "External Link" shows external icon

## Need Review By (Date)
12/20

## Urgency
medium

## Steps to Test
1. In Colorful and Traditional, create a flexible page and add a WYSIWYG block
2. Add a link with a "More link" style and confirm the icon color matches the default colour palette (cardinal)
3. Now add a  link with a "External link" style and confirm the style matches the design in the preview

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

2024-12-19 01:06 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1703-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://hs-colorful-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://hs-traditional-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://english-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://history-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://west-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67637000252c7a7b92db5a28

Visual Diffs:
- https://dashboard.tugboatqa.com/67637000252c7a7b92db5a28/visualdiffs

2024-12-19 23:14 UTC, cienvaras requested changes
@mariannuar Looks good, just a minor change needed.

2024-12-19 23:14 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/utilities/_wysiwyg-text-area.scss
> +  }
This file is used for the styles for the WYSIWYG text blocks in the FE theme. The styles you're adding are only for the CKEditor UI, so please move them in the admin theme CSS (`docroot/themes/humsci/su_humsci_gin_admin/dist/su_humsci_gin_admin.css`).

Also, please add a comment to explain why are you resizing the icon.

2024-12-19 23:24 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1703-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://hs-colorful-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://hs-traditional-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://english-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://history-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://west-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67637000252c7a7b92db5a28

Visual Diffs:
- https://dashboard.tugboatqa.com/67637000252c7a7b92db5a28/visualdiffs

2025-01-02 15:32 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1703-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://hs-colorful-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://hs-traditional-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://english-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://history-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://west-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67637000252c7a7b92db5a28

Visual Diffs:
- https://dashboard.tugboatqa.com/67637000252c7a7b92db5a28/visualdiffs

2025-01-02 15:41 UTC, mariannuar commented
@cienvaras Thanks! Ready for review again!

2025-01-02 22:16 UTC, cienvaras requested changes
@mariannuar Sorry, I missed something in the previous review. Let me know if you have any questions.

2025-01-02 22:16 UTC, cienvaras commented on docroot/themes/humsci/humsci_basic/src/scss/utilities/_wysiwyg-text-area.scss
> +.ck-content a.hs-external-link
Sorry, I missed this one on the previous release, but this is also specific to the editor and shouldn't be in the FE styles. Can you please move this to `docroot/themes/humsci/humsci_basic/src/scss/admin/_wysiwyg-editor.scss`?

2025-01-02 23:03 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1703-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://hs-colorful-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://hs-traditional-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://english-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://history-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://west-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67637000252c7a7b92db5a28

Visual Diffs:
- https://dashboard.tugboatqa.com/67637000252c7a7b92db5a28/visualdiffs

2025-01-02 23:24 UTC, ahughes3 commented
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1703-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://hs-colorful-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://hs-traditional-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://english-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://history-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com
- https://west-wjssscvgy8xojuxe8r2anjaxhxn5homo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67637000252c7a7b92db5a28

Visual Diffs:
- https://dashboard.tugboatqa.com/67637000252c7a7b92db5a28/visualdiffs

2025-01-02 23:26 UTC, mariannuar commented
@cienvaras Updated!

2025-01-03 16:26 UTC, cienvaras requested changes
@mariannuar I just tested on tugboat and the styles are present in the dropdown, but are missing in the text area:

<img width="785" alt="Screenshot 2025-01-03 at 10 15 24 AM" src="https://github.com/user-attachments/assets/0def5593-6b34-463f-9692-a453cbbac19e" />

I think you're missing a class (`ck-content`?)

2025-01-03 16:29 UTC, cienvaras approved these changes
@mariannuar Ignore my previous review, I wasn't using an external link to test, that's why it wasn't working.

2025-01-10 21:57 UTC, pookmish approved these changes

2025-01-10 21:58 UTC, merged