MR-26 Move Hero with Text Overlay into SASS
SU-HSDO/suhumsci pull request #315
Opened 2019-06-27 19:28 UTC by rebeccahongsf

# NOT READY FOR REVIEW

# To Do:
- [x] CSS to SCSS
- [ ] Incorporate multiple color selection
- [ ] Replace with global values if necessary (i.e. colors, breakpoints, etc).

# Summary
- Move Hero with Text Overlay styling from Math-Prod site CSS Injector and into SASS.

# Needed By (Date)
- N/A

# Urgency
- Medium

# Steps to Test
1. Checkout this branch
1. Clear cache
1. View `/patterns/hero_text_overlay` page.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2019-06-28 21:05 UTC, pookmish commented on docroot/themes/humsci/su_humsci_theme/patterns/molecules/hero-text-overlay/scss/hero-text-overlay.scss
> +    &.color-default:before {
Combine this with the rule above. so if there is no class it will always have a color

2019-06-28 21:06 UTC, pookmish commented on docroot/themes/humsci/su_humsci_theme/patterns/molecules/hero-text-overlay/scss/hero-text-overlay.scss
> +    &:hover, &:focus {
Combine this with the rule above:
```
a, 
.decanter-button{
  &:hover,
  &:focus{}
}
```

2019-06-28 21:07 UTC, pookmish commented on docroot/themes/humsci/su_humsci_theme/patterns/molecules/hero-text-overlay/scss/hero-text-overlay.scss
> +@media (min-width: 1500px) {
this can live above with the rest of the styles for the selectors:

```
.hero-text-overlay .image {
  @media (min-width: 1500px) {
  }
}
```

2019-06-28 21:07 UTC, pookmish requested changes
Also dont forget to review code climate

2019-07-01 14:53 UTC, rebeccahongsf commented
Resolved requested changes. 
**Next step:** Review Code Climate and make recommended adjustments/modifications.

2019-07-08 16:58 UTC, pookmish commented on docroot/themes/humsci/su_humsci_theme/patterns/molecules/hero-text-overlay/scss/hero-text-overlay.scss
> +  &.color-default {
I think it might be useful to have a localized mixin. https://sass-lang.com/documentation/at-rules/mixin#arguments

2019-07-08 16:58 UTC, pookmish commented on docroot/themes/humsci/su_humsci_theme/patterns/molecules/hero-text-overlay/scss/hero-text-overlay.scss
> +    .title h2 {
where does the `.title` class come from?

2019-07-08 16:59 UTC, pookmish commented on docroot/themes/humsci/su_humsci_theme/patterns/molecules/hero-text-overlay/scss/hero-text-overlay.scss
> +        background-image: linear-gradient(90deg, #00505c 29.95%, rgba(255, 255, 255, 0) 150%);
would a localized mixin be useful for all these lines too?

2019-07-08 17:00 UTC, pookmish requested changes
Some improvements are possible

2019-07-08 20:47 UTC, rebeccahongsf commented
Reviewing and implementing the improvements now 😄

2019-07-10 18:20 UTC, merged