MR-25 Row with Background
SU-HSDO/suhumsci pull request #317
Opened 2019-06-28 15:43 UTC by rebeccahongsf

# NOT READY FOR REVIEW

# To Do:
- [x] CSS to SCSS

# Summary
- Move Row with background styling from Math-Prod site CSS Injector and into SASS.

# Needed By (Date)
- N/A

# Urgency
- Medium

# Steps to Test
1. Checkout this branch
2. Clear cache

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2019-07-02 14:44 UTC, rebeccahongsf commented
I'll be taking a look and resolving the Code climate issues today!

2019-07-02 21:49 UTC, pookmish commented on docroot/themes/humsci/su_humsci_theme/patterns/molecules/hero-text-overlay/hero-text-overlay.html.twig
> +{% set attributes = attributes.addClass('hero-text-overlay') %}
I dont think this relates to this PR.

2019-07-02 21:49 UTC, pookmish commented on docroot/themes/humsci/su_humsci_theme/patterns/molecules/hero-text-overlay/hero-text-overlay.ui_patterns.yml
> +hero_text_overlay:
I dont think this file relates to this PR.

2019-07-02 21:50 UTC, pookmish requested changes
A couple of files that arent related to the PR here

2019-07-03 15:47 UTC, rebeccahongsf commented
Removed irrelevant files! :)

2019-07-08 17:02 UTC, pookmish commented on docroot/themes/humsci/mathematics/scss/ckeditor.scss
> +'row-with-background';
ckeditor doesnt need this stylesheet included

2019-07-08 17:03 UTC, pookmish commented on docroot/themes/humsci/mathematics/scss/row-with-background.scss
> +@import '../../su_humsci_theme/scss/utilities/mixins/index';
These imports aren't being used in any capacity. we dont need them

2019-07-08 17:03 UTC, pookmish commented on docroot/themes/humsci/mathematics/scss/row-with-background.scss
> +// Mathematics website specific styles.
Update comment

2019-07-08 17:20 UTC, pookmish requested changes
Just some unnecessary imports

2019-07-08 20:46 UTC, merged