refactor: update humsci basic theme scss for namespaced consistency
SU-HSDO/suhumsci pull request #455
Opened 2020-01-27 03:40 UTC by kaseybon

# READY FOR REVIEW

## Summary
This pull request refactors our existing scss to conform our class/variable naming convention:
- We will continue to use BEM as it has been documented.
- We will no longer use class prefixes (`obj`, `util`, and `cmp`) as they only clutter the class names.
- We will namespace all classes, variables, functions (scss), and mixins with `.hb-`.

Documentation regarding namespacing has been added to the Humsci Basic `_main.scss`.

_Note: Right now this PR is dependent on the `STN-105--vertical-card-news` branch. Once that is merged I will update the PR base branch._

## Steps to Test
- [ ] Ensure that the CSS compiles without errors
- [ ] Run `npm test` and ensure that there are not scss linting or test errors
- [ ] Ensure that there are no style changes to the existing template (as compared to `STN-105--vertical-card-news`)
- [ ] Confirm that all Humsci Basic scss has been namespaced

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

2020-01-27 16:04 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/components/_card.scss
> +.hb-card {
on line 95 and 113 there is still something referencing `cmp`

2020-01-27 16:05 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/objects/_layouts.general.scss
> +.hb-page-width {
there is a reference to this in `docroot/themes/humsci/humsci_basic/templates/block/block--local-tasks-block.html.twig` that needs to be changed

2020-01-27 16:05 UTC, silverli requested changes
two small comments! looks good otherwise!

2020-01-30 15:12 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/_main.scss
> +  // All classes, variables, and mixins that belong to the humsci_basic theme will
🎉

2020-01-30 15:41 UTC, bryanbraun commented
I did a quick pass over the code and locally, and everything I saw looked good to me. Thanks for prioritizing this!

2020-01-30 15:55 UTC, silverli approved these changes
Looks awesome! All stylelint and sass tests still pass, and I don't see any non-prefixed variables or classes anymore.

2020-01-30 15:57 UTC, merged