feat(STN-136):  polish horizontal card
SU-HSDO/suhumsci pull request #462
Opened 2020-01-30 17:41 UTC by silverli

# READY FOR REVIEW

## Summary
**Card**: [STN-136](https://sparkbox.atlassian.net/browse/STN-136)
**Author**: @meranicosme 

Polishes and adds refinements for horizontal card, external link, and image zoom hover effect.

## Steps to Test
1. Check out the horizontal card locally. Make sure behavior and style is as expected.
2. In the `humsci_basic` directory, run `npm test` and make sure everything passes.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

2020-01-30 23:58 UTC, heatherdesigns requested changes
![very nice](https://user-images.githubusercontent.com/12678977/73500782-a5d8f700-4391-11ea-9a01-64f85508e2c6.gif)

Great work tackling these refinements! :tada:

I left some comments throughout the code base. I'm available to answer any questions you have and/or to pair.

I also noticed some duplicates of existing files. Perhaps something happened during a rebase. 🤷‍♀It happens. :smile: I'm including screenshots below of the duplicate files. Look for the files with `2` added to the file name at the end. Make sure all of your changes are in the original files, then delete the duplicate files.

<img width="1010" alt="grid duplicates" src="https://user-images.githubusercontent.com/12678977/73501055-770f5080-4392-11ea-9ac4-1b5284833fe1.png">

<img width="1012" alt="component duplicates" src="https://user-images.githubusercontent.com/12678977/73501062-7971aa80-4392-11ea-9ae5-30cf0e0ad80c.png">

<img width="1012" alt="tools duplicate" src="https://user-images.githubusercontent.com/12678977/73501064-7bd40480-4392-11ea-93a1-8cd2d5c537b3.png">

2020-01-30 23:58 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.fonts.scss
> +    color: red;
This is great!!! :smile: `color` and `background-color` are so good for testing!

2020-01-30 23:58 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/elements/_base.scss
> +        background: svg('<svg viewBox="0 0 12 12"><path d="M11.273 5.818v5.455H.727V.727h5.091m1.455 0h4v4m0-4L6.182 5.818" fill="transparent" stroke="#{$hb-color--primary}" stroke-width="2" stroke-m
Targeting the stroke color in the SVG. Bravo! :tada:

2020-01-30 23:58 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/components/_card.scss
> +          transform: scale(1.07);
Nice!! This looks great! :smile:

2020-01-30 23:58 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/components/_node--news-item 2.scss
> +  }
Just an FYI. You don't need to make any changes as there are multiple ways to do the same thing. :wink:
Lines 50 through 56 can also be written like this:
```
.field-hs-news-date,
.field-hs-news-link {
    line-height: 1.4;
}
```

2020-01-30 23:58 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.fonts.scss
> +// }
Clean up task --> remove commented code on lines 130 to 150. (I do this too! 🙈)

2020-01-30 23:58 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/objects/_layouts.general.scss
> +}
Lines 15 through 23 look to be duplicated styles. We can remove them.

Here's the output from `npm run test`
<img width="580" alt="npm run test" src="https://user-images.githubusercontent.com/12678977/73494408-78388180-4382-11ea-8878-8b36a4855ace.png">

2020-01-30 23:58 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/elements/_base.scss
> +.field-hs-news-link a {
Let's move the styles for `.field-hs-news-link a` into `docroot/themes/humsci/humsci_basic/src/scss/components/_node--news-item.scss` alongside the other `.field-hs-news` classes.

2020-01-30 23:58 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_functions.svg 2.scss
> +// http://codepen.io/tigt/post/optimizing-svgs-in-data-uris
Love this! Taylor Hunt is a CSS guru.

2020-01-30 23:58 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.fonts.scss
>  @mixin hb-link {
I'm seeing a different link style on headings. This is what I see.
<img width="369" alt="heading" src="https://user-images.githubusercontent.com/12678977/73499700-cf445380-438e-11ea-886c-c24be0087ecd.png">

I _think_ we need to include this mixin on `hb-card__title` headings with links. That would affect all cards that have headings with links. Let's look at this together just to make sure. 👀

2020-01-31 17:13 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/templates/layouts/three_column_w_image.html.twig
> +
Sorry I didn't catch this earlier! It looks like lines 11 through 18 are duplicated.

2020-01-31 20:32 UTC, closed without merging

2020-01-31 20:32 UTC, meranicosme commented
Created new PR due to branch rebasing conflicts, with past sprint.