WIP: feat(STN-99):  secondary nav and styling
SU-HSDO/suhumsci pull request #468
Opened 2020-02-03 15:42 UTC by silverli

# NOT READY FOR REVIEW

## Summary
Adds HTML markup and styling for secondary nav.

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

2020-02-03 18:29 UTC, silverli commented
## Screenshots thus far

![Screen Shot 2020-02-03 at 1 04 57 PM](https://user-images.githubusercontent.com/12848168/73679808-26953d00-4689-11ea-85d0-4df1678fb9e5.png)
![Screen Shot 2020-02-03 at 1 07 49 PM](https://user-images.githubusercontent.com/12848168/73679809-26953d00-4689-11ea-8a75-07478d1b7a88.png)
![Screen Shot 2020-02-03 at 1 14 57 PM](https://user-images.githubusercontent.com/12848168/73679810-26953d00-4689-11ea-80b6-f2c6d634cf91.png)
![Screen Shot 2020-02-03 at 1 16 37 PM](https://user-images.githubusercontent.com/12848168/73679812-26953d00-4689-11ea-9b81-f2be55b95c30.png)

2020-02-04 17:00 UTC, kaseybon commented on docroot/themes/humsci/humsci_basic/src/scss/components/_secondary-nav.scss
> +    &[aria-expanded="true"] {
I love targeting aria attributes for these types of styles!

2020-02-04 17:00 UTC, kaseybon commented on docroot/themes/humsci/humsci_basic/templates/menus/macros/secondary-nav-menu.twig
> +    {# {% if item.is_active == true %}
Should we delete these comments?

2020-02-04 17:00 UTC, kaseybon commented on docroot/themes/humsci/humsci_basic/templates/menus/macros/secondary-nav-menu.twig
> +    {# {% if item.is_active == true %}
Same thing on lines 29 and 41.

2020-02-04 17:02 UTC, kaseybon requested changes
Everything looks good except we don't have any focus states for the show/hide toggles.

2020-02-04 17:07 UTC, silverli commented on docroot/themes/humsci/humsci_basic/templates/menus/macros/secondary-nav-menu.twig
> +    {# {% if item.is_active == true %}
yep thank you

2020-02-04 17:30 UTC, kaseybon approved these changes

2020-02-04 17:36 UTC, merged