Sparkbox Sprint 8
SU-HSDO/suhumsci pull request #498
Opened 2020-02-25 01:35 UTC by kaseybon

* feat: add WYSIWYG styles

JIRA STN-127 https://sparkbox.atlassian.net/browse/STN-127

* feat: add config settings so that the WYSIWYG displays the correct theme styles within the editor

* refactor: move styles out of utilities and into elements

The WYSIWYG styles are more of an element such as a form or table, than a utility.

* feat: move blockquote styles outside of the field-hs-text-area class to allow the styles to render within the WYSIWYG editor

# READY FOR REVIEW

## Summary
_[briefly summarize the changes here]_

## Need Review By (Date)
_['10/30', 'asap', etc.]_

## Urgency
_['low', 'medium', 'high', etc.]_

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

2020-02-25 02:24 UTC, pookmish commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr498-x5eyppcnpidw1z9tdfpnbjvg9wjmt5q0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e548245008a56cb813fc647

2020-02-25 15:48 UTC, pookmish commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr498-x5eyppcnpidw1z9tdfpnbjvg9wjmt5q0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e548245008a56cb813fc647

2020-02-26 02:07 UTC, pookmish commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr498-x5eyppcnpidw1z9tdfpnbjvg9wjmt5q0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e548245008a56cb813fc647

2020-02-26 16:55 UTC, pookmish requested changes
I've also noticed the behat tests are failing. I'll open a PR and request that be fixed as part of this

2020-02-26 16:55 UTC, pookmish commented on docroot/themes/humsci/humsci_colorful/theme-settings.php
> +use Drupal\Core\Render\Markup;
unsused `use` statements

2020-02-26 20:31 UTC, kaseybon commented on docroot/themes/humsci/humsci_colorful/theme-settings.php
> +use Drupal\Core\Render\Markup;
@pookmish I pushed a fix removing those statements.

2020-02-26 21:08 UTC, pookmish commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr498-x5eyppcnpidw1z9tdfpnbjvg9wjmt5q0.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e548245008a56cb813fc647

2020-02-27 17:39 UTC, merged