WIP feat(STN-337):  tradl theme work
SU-HSDO/suhumsci pull request #579
Opened 2020-04-27 23:08 UTC by silverli

# READY FOR REVIEW

## Summary
More work to get tradl theme to have colorful logic, HTML, and CSS as base styles wherever possible so everything works out of the box.

Note: heros are not working yet. it feelsl like a complex one since they vary a lot theme to theme.

## Steps to Test
1. In humsci_basic, `npm run test` passes.
2. Check the site. Should look very similar to Sand Colorful theme pairing, except for headings, and some link and button styles. Everything should work out of the box.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

2020-04-27 23:09 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/components/_buttons.scss
> +    &:hover {
maybe there should be focus here too?

2020-04-28 21:06 UTC, bryanbraun requested changes
This is looking really good so far. I have a couple of comments with things to look into. I'm also doing a more detailed local-dev scan of the site right now, but I wanted to get this feedback to you right away... I'll ping you if I add any additional comments.

***

_Additional comments from local testing:_

Based on the most designs, these footer headings aren't supposed to have a serif font.

![image](https://user-images.githubusercontent.com/1256329/80540193-d15e8400-8976-11ea-8063-811bea1eae0e.png)

(I'm comfortable with addressing this in https://sparkbox.atlassian.net/browse/STN-344, though, given the time-sensitivity of this work)

2020-04-28 21:06 UTC, bryanbraun commented on docroot/themes/humsci/humsci_basic/src/scss/components/_buttons.scss
> +    &:hover {
I looked at this, and I think it's probably ok as-is. This button is inheriting some focus styles from the `@include button-style;` at the top. If we forced the hover and focus styles to be the same, then the focus styles may be a bit to subtle.

2020-04-28 21:06 UTC, bryanbraun commented on docroot/themes/humsci/humsci_basic/src/scss/components/_pager.scss
> +        &:focus {
Nice job adding these focus states in here! 💪

2020-04-28 21:06 UTC, bryanbraun commented on docroot/themes/humsci/humsci_basic/src/scss/components/_vertical-linked-card.scss
> +
This code seems to be the same as the code in the colorful/airy condition above... do we need these to be separated right now? Or is it just to plan for future changes?

2020-04-28 21:06 UTC, bryanbraun commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.text.scss
> +  }
This new mixin is fantastic! 💯

2020-04-28 21:06 UTC, bryanbraun commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.buttons.scss
> +  @include hb-global-color('color', 'white', $important: true);
I'm seeing an issue on the secondary button focus state... I'm not sure if it's related to this line of code, but possibly?

![image](https://user-images.githubusercontent.com/1256329/80536856-0cf64f80-8971-11ea-8d74-f46d7219831a.png)

2020-04-28 21:06 UTC, bryanbraun commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.text.scss
> +    font-size: hb-calculate-rems(14px);
Hm, where are these differences coming from. The designs?

2020-04-29 16:15 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/components/_vertical-linked-card.scss
> +
it is slightly different. I can potentially try to DRY this up a bit, but this uses the ht-traditional palette, whereas the other one uses the hc-colorful palette

2020-04-29 16:57 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.buttons.scss
> +  @include hb-global-color('color', 'white', $important: true);
it was something else I forgot in the utilities. I wrote a note because that code should be refactored to use mixins more

2020-04-29 16:58 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.text.scss
> +    font-size: hb-calculate-rems(14px);
yeah that's how I read it

2020-04-29 19:50 UTC, bryanbraun commented on docroot/themes/humsci/humsci_basic/src/scss/components/_vertical-linked-card.scss
> +
Oh I must have missed those differences. Either way is ok for me. 👍

2020-04-29 20:32 UTC, bryanbraun approved these changes

2020-04-29 21:40 UTC, merged