STN-362: Card Image Utilities
SU-HSDO/suhumsci pull request #601
Opened 2020-05-15 16:11 UTC by kaseybon

# READY FOR REVIEW

## Summary
This PR adds a set of responsive utility classes to customize the width of images in card components. Classes can be applied to horizontal cards, vertical cards, and structured cards. Classes must be applied to the entire view (not just the image) and will follow a similar naming convention to the [Decanter Grid System](https://decanter.stanford.edu/page/layouts-grid-system/):
- `hb-card-image-4-of-12` sets the image to 1/4th the width of the card at all screen sizes
- `hb-card-image-md-4-of-12` sets the image to 1/4th the width of the card at the medium break point and larger

These classes have been documented in the H&S Pattern Documentation.

There should be no change to any existing card patterns, the change is purely additive.

## Need Review By (Date)
05/18/2020

## Urgency
medium

## Steps to Test
1. Confirm that all tests pass
2. Confirm that all card patterns have not changed in their default state
3. Modify a view and apply the following classes to the entire view:
    `hb-card-image-12-of-12 hb-card-image-sm-6-of-12 hb-card-image-md-3-of-12`
    <img width="1751" alt="Custom_Econ_News__Content____Department_of_Economics" src="https://user-images.githubusercontent.com/2486846/82070804-4209de00-96a3-11ea-9507-05e2a33a529d.png">
    This should cause the width of the image to be 100% of the card at the smallest screen sizes then change to 50% at the small breakpoint, and then be 25% of the width at the medium breakpoint.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

2020-05-15 22:25 UTC, heatherdesigns requested changes
Fantastic idea creating utility classes that are similar to those used in the local footer which is something H&S is familiar with! 🏆 

When `hb-card-image-6-of-12` and above are used on horizontal and structured cards there is an overflow of content and horizontal scroll. I think the values of flex and max-width in `hb-card__content` need to be adjusted as well. When an image is using `flex-column(7)`, then the content needs `flex-column(5)` to prevent overflow and horizontal scroll.

2020-05-15 22:25 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/utilities/_card-images.scss
> +  @for $i from 1 through 12 {
These screenshots are from http://economics.suhumsci.loc/about/news.
At `6-of-12` the content overflows the containing div of `hb-card--horizontal`.

![6-of-12](https://user-images.githubusercontent.com/12678977/82099125-83ff4800-96d4-11ea-82c0-e1f9565d9761.png)

<br><br>

At `7-of-12` and above the content causes horizontal scroll in Safari and is cut off in Chrome. This is at a scrren width of ~1200px.

![chrome](https://user-images.githubusercontent.com/12678977/82099246-e0fafe00-96d4-11ea-8518-73d9cca7897d.png)

<br><br>

`6-of-12` and above also do not work well with a 2nd sidebar. This screenshot is with an image at `7-of-12`.

![with 2nd sidebar](https://user-images.githubusercontent.com/12678977/82099584-af366700-96d5-11ea-958e-18fb1c58e258.png)

2020-05-15 22:25 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/utilities/_card-images.scss
> +  @for $i from 1 through 12 {
The vertical cards are fine. And they would benefit the most from `6-of-12` and up. Anything smaller looks awkward. I hate to say that we may need different utility classes for vertical and horizontal cards, but maybe?

2020-05-18 13:55 UTC, kaseybon commented
@heatherdesigns I fixed the utility classes to also adjust the width of the content area.

2020-05-18 14:55 UTC, heatherdesigns approved these changes

2020-05-18 14:55 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/utilities/_card-images.scss
> +          @include flex-column(12 - $i);
Nice!! 🏆

2020-05-18 15:05 UTC, merged