STN-351: QA Feedback 16
SU-HSDO/suhumsci pull request #608
Opened 2020-05-20 14:56 UTC by heatherdesigns

# [STN-372](https://sparkbox.atlassian.net/browse/STN-351)  🛑NOT READY FOR REVIEW

## Summary
Resolve issues discovered during the Sprint 16 QA Feedback session listed in STN-351

## Need Review By (Date)
5/26

## Urgency
medium

## Steps to Test
1. In the CLI run `npm run test` and confirm all of our Sass tests pass.
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

2020-05-21 23:19 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/components/_card.scss
> +      [class*="views-label-field-hs-event-date"] + .field-content {
We are using classes generated by Drupal for the styling of the icons. Targeting `.views-label-field-hs-event-date` is fine for the highlight events but the icons were not displaying for the list of upcoming seminars. I discovered upcoming seminars has a different class name of `.views-label-field-hs-event-date-5`. I'm unsure how Drupal generates the `-5` and assume this number could be different when the date stacked horizontal pattern is used on another view. The change introduced was the only way I could think of targeting all potential scenarios.

2020-05-26 12:50 UTC, kaseybon commented on docroot/themes/humsci/humsci_basic/src/scss/objects/_layouts.row.scss
> +    // When there is only one accordion in the row, make it grow to the entire width. This property is not needed on accordions when they are placed in a row with other items.
👏

2020-05-26 13:02 UTC, kaseybon commented
There are some issues with the image overlapping the on pages with 3 columns:
http://economics.suhumsci.loc/people/christopher-makler

<img width="1285" alt="Screen Shot 2020-05-26 at 9 01 20 AM" src="https://user-images.githubusercontent.com/2486846/82903840-90cf3780-9f2f-11ea-90b6-5c9a9bcf23ff.png">

2020-05-26 14:43 UTC, heatherdesigns commented
## Issue discovered while browser testing:

Hero in row looks fine in Safari, but doesn't expand the full width in Chrome as some breakpoints.
![safari left vs chrome right](https://user-images.githubusercontent.com/12678977/82914661-c8dd7700-9f3d-11ea-8c63-f2f26bff649f.png)

2020-05-26 15:26 UTC, heatherdesigns commented
I added the `word-break` property to allow the content beside images to collapse as needed. Unfortunately this could get ugly if used with large images. In my local environment I updated the image styles to used `Small Square 200 x 200` for the person node detail pages because of the 2 column column. I will share this at demo.

![faculty node](https://user-images.githubusercontent.com/12678977/82919191-b5350f00-9f43-11ea-9c43-6bd94e9df3d3.png)

2020-05-26 16:36 UTC, silverli requested changes
one last small thing I noted is that for an accordion with a very long title, it needs bit more padding around the arrow so they dont overlap

<img width="1213" alt="Screen Shot 2020-05-26 at 12 19 54 PM" src="https://user-images.githubusercontent.com/12848168/82926624-7c019c80-9f4d-11ea-99cc-76867c76a899.png">

2020-05-26 18:13 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/objects/_layouts.row.scss
> +            padding-right: hb-calculate-rems(52px);
👍

2020-05-26 19:20 UTC, silverli approved these changes
Looks great!! Awesome and thorough job on all this!

2020-05-26 19:21 UTC, merged