STN: 173  Simplify Templates
SU-HSDO/suhumsci pull request #614
Opened 2020-05-28 13:56 UTC by heatherdesigns

# 🛑  [STN-173](https://sparkbox.atlassian.net/browse/STN-350) NOT READY FOR REVIEW

## Summary
Simplify templates as a result of the `empty fields` bugfix.

## Need Review By (Date)
5/29

## Urgency
medium

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

2020-05-28 21:47 UTC, silverli requested changes
See my comments in your PR description that are in italics. There seems to be an issue with this page and view using vertical linked postcards: http://economics.suhumsci.loc/research/research-fields

2020-05-29 21:39 UTC, heatherdesigns commented
Regarding http://economics.suhumsci.loc/research/research-fields I discovered the Vertical Linked Cards on this page are generated via a view. Whereas the Vertical Linked Cards on the QA Cards page are generated via postcards.

2020-06-01 22:04 UTC, silverli commented
I am seeing that for all views, you cannot use the "hide empty fields" checkbox for all mappings in the pattern. if you do, the link to content renders as null always.

2020-06-01 23:14 UTC, silverli approved these changes
Great work!

2020-06-01 23:19 UTC, merged