STN-325: Private Pages
SU-HSDO/suhumsci pull request #636
Opened 2020-06-23 17:05 UTC by kaseybon

# READY FOR REVIEW

## Summary
This pull request adds the following:
- A lock icon to the left of the title in private pages
- A lock icon to the left of the link text for private pages in the main nav and menu blocks
- A utility class (`hs-private-link`) that adds a lock icon to the left of link text in WYSIWYG editors

Work has been reviewed in the following browsers:
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11

## Need Review By (Date)
6/25

## Urgency
medium

## Steps to Test
1. Run `npm test`
2. Import changes to the ckeditor config files
3. Create a new private page (content -> private page) and add the page to the main navigation
4. - [ ] There should be a lock icon next the link the main and secondary navigation regardless of the nesting level (see video in Jira card for more details on what this should look like)
    <img width="1298" alt="Private_Page___Department_of_Economics_and_Slack_____-general___Sparkbox" src="https://user-images.githubusercontent.com/2486846/85432907-a006cc80-b551-11ea-8e21-69f58ca73a03.png">
5. - [ ] There should be a lock icon next to the title of the private page.
    <img width="1298" alt="Private_Page___Department_of_Economics_and_Slack_____-general___Sparkbox" src="https://user-images.githubusercontent.com/2486846/85432862-941b0a80-b551-11ea-8fc7-68f4c3aea916.png">
6. - [ ] There should be an option to add the `hs-private-link` class to inline links in the ckeditor

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

2020-06-25 16:10 UTC, silverli commented on docroot/themes/humsci/humsci_basic/humsci_basic.theme
> +      if ($node && $type == 'hs_private_page') {
cool!

2020-06-26 20:46 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/components/_private.scss
> +.private-page {
should we call this file private-page?

2020-06-26 20:47 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_functions.icons.scss
> +  } @else if ($icon == 'lock') {
👍

2020-06-26 20:48 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/components/_private.scss
> +.hb-private-page-link {
I think this should go in utilities? or no?

2020-06-26 20:49 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/components/_private.scss
> +.hs-private-link {
I think this should go in the utilities file right?

2020-06-26 20:51 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/components/_private.scss
> +    @include grid-media-min('lg') {
nice!!

2020-06-26 20:51 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/components/_private.scss
> +      background-size: hb-calculate-rems(15px) hb-calculate-rems(15px);
also a good edge case catch!

2020-06-26 20:52 UTC, silverli requested changes
Hey this looks great! Just one or two questions and then upon reviewing I saw this one tiny potential bug:

<img width="488" alt="Screen Shot 2020-06-26 at 4 45 54 PM" src="https://user-images.githubusercontent.com/12848168/85900181-5a563800-b7cd-11ea-9786-fb58dd0a731b.png">

2020-06-26 21:10 UTC, kaseybon commented
@silverli since it's an inline pseudo element that can happen at some screen sizes. It's the same thing with the external link icon as well.
<img width="880" alt="Screen_Shot_2020-06-26_at_4_59_49_PM" src="https://user-images.githubusercontent.com/2486846/85901427-d5205280-b7cf-11ea-8af8-4bf3e7a8a435.png">

2020-06-29 14:46 UTC, silverli commented on docroot/themes/humsci/humsci_basic/src/scss/utilities/_wysiwyg-text-area.scss
> +.hs-private-link {
👏

2020-06-29 14:57 UTC, silverli approved these changes
looks great!!

2020-06-29 15:14 UTC, merged