Sparkbox sprint 19
SU-HSDO/suhumsci pull request #642
Opened 2020-06-29 22:49 UTC by silverli

# Ready for Review

## Summary
Changes and stories addressed in Sparkbox Sprint 19:

- QA Feedback Part 1 (Sprint 17) | [STN-379](https://sparkbox.atlassian.net/browse/STN-379) #623 
- QA Feedback Part 2 (Sprint 17.2) | [STN-414](https://sparkbox.atlassian.net/browse/STN-414) #627 
- Feat: back to top custom block (for long pages)  | [STN-263](https://sparkbox.atlassian.net/browse/STN-263) #628 
- Small fix: hb-categories | #630

### TASK LIST:
- [ ] Add compiled CSS & JS
- [ ] Ensure Code Climate passes against the `develop` branch. 
- [ ] Assign to Mike for review.

## Need Review By (Date)
7/1

## Urgency
high

## Steps to Test
1. `npm run test` should pass in the root folder
2. If you are interested in the testing steps for associated PRs, please take a look at the individual PR's description and "Steps to Test" section.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

2020-06-30 21:00 UTC, silverli commented
@pookmish this should be all set for you to review. Please let @kaseybon or myself know if you have any questions. Additionally, please let us know if there's anything you foresee us needing to do to in order to prepare to move to Drupal 9 at some point. Thanks!

2020-06-30 21:37 UTC, pookmish requested changes

2020-06-30 21:37 UTC, pookmish commented on docroot/themes/humsci/humsci_basic/patterns/spotlight/spotlight.ui_patterns.yml
> +spotlight:
Can you please add this to the old theme. it doesn't need to have the styling, but the pattern has to be available in each theme that is available.

2020-07-01 16:14 UTC, pookmish approved these changes

2020-07-01 16:15 UTC, merged