[WIP] Sparkbox Sprint 22
SU-HSDO/suhumsci pull request #681
Opened 2020-08-11 14:06 UTC by kaseybon

# READY FOR REVIEW

## Summary
_[briefly summarize the changes here]_

## Need Review By (Date)
_['10/30', 'asap', etc.]_

## Urgency
_['low', 'medium', 'high', etc.]_

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

2020-08-12 20:54 UTC, pookmish requested changes
Just a couple small changes requested

2020-08-12 20:54 UTC, pookmish commented on .circleci/config/behat.yml
> +        banner: ".paragraph--type--hs-banner"
That't not really a region. This shouldn't go here

2020-08-12 20:54 UTC, pookmish commented on docroot/themes/humsci/humsci_basic/humsci_basic.theme
> +
No empty lines after a comment. also this comment line is too long. Code climate should have picked that up. This comment could go below the `Implements` in the docblock.

2020-08-13 16:37 UTC, kaseybon commented
@pookmish should be all set now

2020-08-13 16:47 UTC, pookmish approved these changes

2020-08-13 16:48 UTC, merged