STN-777: Color band sidebar refinement
SU-HSDO/suhumsci pull request #892
Opened 2021-05-28 23:46 UTC by rkelbel

# NOT READY FOR REVIEW

This is still a WIP, I have only tested with custom blocks, we have other blocks to test and also questions around padding between the left and right sides of blocks that have color bands going across them.

## Summary
_[briefly summarize the changes here]_

## Need Review By (Date)
_['10/30', 'asap', etc.]_

## Urgency
_['low', 'medium', 'high', etc.]_

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

2021-06-04 17:30 UTC, heatherdesigns requested changes
Fantastic work on the color band refinement! This is looking sooooo much better! :tada:

I was able to apply the `hb-well` class to a block in the sidebar as seen on the [Upcoming Events and Seminars page](https://economics.stanford.edu/seminars-events/upcoming-seminars-and-events) on the Economics site.

It looks like the background-color of `hb-well` is being overwritten by the background-color set for sidebar utility class.

![hb-well](https://user-images.githubusercontent.com/12678977/120841046-030e2b00-c539-11eb-90fe-893f599848e7.png)

2021-06-04 17:30 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.general.scss
> +    z-index: 1;
Let's use a variable from `humsci_basic/src/scss/settings/_variables.zindex.scss` for the value of `1`.

2021-06-04 17:30 UTC, heatherdesigns commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.layout.scss
> +@mixin hb-sidebar-block {
I love a good mixin! Nice work!! :tada:

2021-06-07 16:21 UTC, rkelbel commented on docroot/themes/humsci/humsci_basic/src/scss/tools/_mixins.general.scss
> +    z-index: 1;
This has been fixed, also found a second place we needed to update this and did that at the same time.

2021-06-07 16:23 UTC, rkelbel commented
> I was able to apply the `hb-well` class to a block in the sidebar as seen on the [Upcoming Events and Seminars page](https://economics.stanford.edu/seminars-events/upcoming-seminars-and-events) on the Economics site.
> 
> It looks like the background-color of `hb-well` is being overwritten by the background-color set for sidebar utility class.

So I found that since those classes were moved to a mixin, the hierarchy in how they are applied have changed. I tried a few options but I would lose the background color on the nav sidebars if I removed it and moved it to the block utility class.

So I added the well mixin to the sidebar to catch this application.

Let me know if you have additional ideas here, but right now it should be working correctly.

2021-06-07 18:30 UTC, heatherdesigns approved these changes

2021-06-07 21:51 UTC, merged